tank_drive_node:
  ros__parameters:
    cmd_topic: "cmd_vel_safe"
    ena_right: 12
    enb_left: 13
    in1: 5
    in2: 6
    in3: 16
    in4: 26
    pwm_frequency_hz: 1000
    max_pwm: 200
    min_pwm: 80
    max_linear_mps: 0.5
    max_angular_rads: 1.0
    cmd_timeout_s: 0.5
    control_rate_hz: 20.0
    log_debug: true
