ultrasonic_node:
  ros__parameters:
    min_range_m: 0.005
    max_range_m: 2.0
    publish_rate_hz: 10.0
    inter_sensor_delay_ms: 60
    treat_too_close_as_min_range: true
    log_debug: false
    filter_window: 1
    trim_size: 0
    enable_front: true
    enable_back: true
    enable_left: true   # set true when left sensor is physically wired
    enable_right: true  # set true when right sensor is physically wired

imu_node:
  ros__parameters:
    i2c_device: "/dev/i2c-1"
    i2c_address: 83  # 0x53
    publish_rate_hz: 50.0
    frame_id: "imu_link"
