slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: mapping
    stack_size_to_use: 40000000
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    scan_topic: /scan_ultra
    scan_queue_size: 1
    throttle_scans: 5
    minimum_time_interval: 1.0
    tf_buffer_duration: 30.0
    transform_publish_period: 0.2
    map_update_interval: 3.0
    resolution: 0.10
    max_laser_range: 4.0
    minimum_travel_distance: 0.05
    minimum_travel_heading: 0.05
